# Site settings
title:KinKinetics
email:kinkinetics@outlook.com
description: > # Enhancing astronaut resilience and productivity through innovative emotional and psychological support technologies for long-duration space missions."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://Qetsiyeh.github.io" # the base hostname & protocol for your site

twitter_username:
github_username: Qetsiyeh

# Build settings
markdown: kramdown
